animals = [
    "Jaguar",
    "Orangutan",
    "Nightingale",
    "Deer",
    "Kingfisher",
    "Raccoon",
    "Anaconda",
    "Bass",
    "Herring",
    "Wildcat",
    "Cat",
    "Lark",
    "Crawdad",
    "Manatee",
    "Leopard",
    "Wombat",
    "Sheep",
    "Python",
    "Armadillo",
    "Pig",
    "Wasp",
    "Peafowl",
    "Vole",
    "Scorpion",
    "Tarantula",
    "Lemming",
    "Silkworm",
    "Rat",
    "Crayfish",
    "Mule",
    "Dormouse",
    "Cardinal",
    "Primate",
    "Jellyfish",
    "Salamander",
    "Porpoise",
    "Bee",
    "Donkey",
    "Marmot",
    "Gecko",
    "Heron",
    "Lynx",
    "Rhinoceros",
    "Panther",
    "Leech",
    "Goldfish",
    "Clownfish",
    "Chipmunk",
    "Swordfish",
    "Squid",
    "Blackbird",
    "Flea",
    "Aphid",
    "Mongoose",
    "Ermine",
    "Centipede",
    "Toucan",
    "Chicken",
    "Viper",
    "Jay",
    "Kangaroo",
    "Gerbil",
    "Dingo",
    "Magpie",
    "Slug",
    "Termite",
    "Catshark",
    "Bobcat",
    "Whippet",
    "Mite",
    "Tortoise",
    "Sloth",
    "Eagle",
    "Seahorse",
    "Rooster",
    "Earwig",
    "Cobra",
    "Pike",
    "Trout",
    "Lungfish",
    "Flamingo",
    "Woodpecker",
    "Chameleon",
    "Sturgeon",
    "Asp",
    "Aardvark",
    "Pelican",
    "Wildebeest",
    "Stingray",
    "Beetle",
    "Pheasant",
    "Firefly",
    "Haddock",
    "Hippopotamus",
    "Spoonbill",
    "Whitefish",
    "Sawfish",
    "Leopon",
    "Thrush",
    "Quokka",
    "Goose",
    "Hummingbird",
    "Lobster",
    "Yak",
    "Otter",
    "Locust",
    "Buzzard",
    "Moth",
    "Wallaby",
    "Hawk",
    "Ant",
    "Alpaca",
    "Bandicoot",
    "Goat",
    "Possum",
    "Harrier",
    "Marlin",
    "Lemur",
    "Badger",
    "Mockingbird",
    "Capybara",
    "Shrimp",
    "Grasshopper",
    "Guppy",
    "Octopus",
    "Anteater",
    "Dove",
    "Antlion",
    "Dolphin",
    "Zebra",
    "Bat",
    "Marsupial",
    "Cow",
    "Salmon",
    "Wolverine",
    "Porcupine",
    "Egret",
    "Basilisk",
    "Whale",
    "Toad",
    "Elephant",
    "Lizard",
    "Jackal",
    "Impala",
    "Carp",
    "Puffin",
    "Cougar",
    "Piranha",
    "Lion",
    "Cod",
    "Beaver",
    "Cattle",
    "Cuckoo",
    "Camel",
    "Penguin",
    "Sparrow",
    "Crane",
    "Ladybug",
    "Anglerfish",
    "Kiwi",
    "Ostrich",
    "Sailfish",
    "Catfish",
    "Butterfly",
    "Panda",
    "Loon",
    "Mackerel",
    "Mandrill",
    "Platypus",
    "Orca",
    "Alligator",
    "Rattlesnake",
    "Wolf",
    "Tiger",
    "Echidna",
    "Falcon",
    "Shark",
    "Swallow",
    "Pinniped",
    "Minnow",
    "Ox",
    "Swan",
    "Opossum",
    "Pigeon",
    "Barnacle",
    "Smelt",
    "Moose",
    "Lamprey",
    "Eel",
    "Ocelot",
    "Marmoset",
    "Peacock",
    "Puma",
    "Warbler",
    "Walrus",
    "Pony",
    "Bonobo",
    "Mouse",
    "Crab",
    "Bear",
    "Ape",
    "Boar",
    "Partridge",
    "Aardwolf",
    "Meadowlark",
    "Skunk",
    "Llama",
    "Vicuna",
    "Halibut",
    "Louse",
    "Mole",
    "Cricket",
    "Cheetah",
    "Dragonfly",
    "Bird",
    "Turkey",
    "Parakeet",
    "Ferret",
    "Grouse",
    "Chickadee",
    "Albatross",
    "Mink",
    "Reindeer",
    "Booby",
    "Worm",
    "Crocodile",
    "Iguana",
    "Clam",
    "Marten",
    "Hornet",
    "Scallop",
    "Condor",
    "Shrew",
    "Angelfish",
    "Cockroach",
    "Raven",
    "Parrot",
    "Dog",
    "Parrotfish",
    "Gazelle",
    "Antelope",
    "Spider",
    "Baboon",
    "Macaw",
    "Turtle",
    "Caribou",
    "Gull",
    "Koala",
    "Newt",
    "Duck",
    "Narwhal",
    "Fish",
    "Guineafowl",
    "Giraffe",
    "Coral",
    "Hamster",
    "Emu",
    "Koi",
    "Crow",
    "Quelea",
    "Swordtail",
    "Hedgehog",
    "Bison",
    "Caterpillar",
    "Limpet",
    "Roadrunner",
    "Tuna",
    "Boa",
    "Gibbon",
    "Mollusk",
    "Starfish",
    "Horse",
    "Flyingfish",
    "Weasel",
    "Quail",
    "Hare",
    "Rabbit",
    "Meerkat",
    "Muskox",
    "Mastodon",
    "Stoat",
    "Barracuda",
    "Planarian",
    "Chinchilla",
    "Fox",
    "Roundworm",
    "Monkey",
    "Earthworm",
    "Gopher",
    "Vulture",
    "Elk",
    "Finch",
    "Rook",
    "Cicada",
    "Stork",
    "Prawn",
    "Perch",
    "Rodent",
    "Frog",
    "Owl",
    "Snail",
    "Coyote",
    "Squirrel",
    "Tapir",
    "Mosquito",
    "Chimpanzee",
    "Gorilla",
    "Snake",
    "Hyena",
    "Wren",
]

colors = [
    {"cname": "Russet", "hex": "#A13905"},
    {"cname": "Midnight", "hex": "#03012d"},
    {"cname": "Rose", "hex": "#Cf6275"},
    {"cname": "Viridian", "hex": "#1e9167"},
    {"cname": "Twilight", "hex": "#4e518b"},
    {"cname": "Charcoal", "hex": "#343837"},
    {"cname": "Ecru", "hex": "#Feffca"},
    {"cname": "Bile", "hex": "#B5c306"},
    {"cname": "Copper", "hex": "#B66325"},
    {"cname": "Pea", "hex": "#A4bf20"},
    {"cname": "Tan", "hex": "#D1b26f"},
    {"cname": "Mauve", "hex": "#Ae7181"},
    {"cname": "Dusk", "hex": "#4e5481"},
    {"cname": "Sepia", "hex": "#985e2b"},
    {"cname": "Tangerine", "hex": "#Ff9408"},
    {"cname": "Fawn", "hex": "#Cfaf7b"},
    {"cname": "Navy", "hex": "#01153e"},
    {"cname": "Seafoam", "hex": "#80f9ad"},
    {"cname": "Yellowish", "hex": "#Faee66"},
    {"cname": "Cobalt", "hex": "#1e488f"},
    {"cname": "Seaweed", "hex": "#18d17b"},
    {"cname": "Ice", "hex": "#D6fffa"},
    {"cname": "Vermillion", "hex": "#F4320c"},
    {"cname": "Silver", "hex": "#C5c9c7"},
    {"cname": "Gunmetal", "hex": "#536267"},
    {"cname": "Piss", "hex": "#Ddd618"},
    {"cname": "Coffee", "hex": "#A6814c"},
    {"cname": "Chestnut", "hex": "#742802"},
    {"cname": "Brick", "hex": "#A03623"},
    {"cname": "Raspberry", "hex": "#B00149"},
    {"cname": "Pea-green", "hex": "#C4fe82"},
    {"cname": "Pale", "hex": "#Fff9d0"},
    {"cname": "Clay", "hex": "#B66a50"},
    {"cname": "Bluish", "hex": "#2976bb"},
    {"cname": "Leather", "hex": "#Ac7434"},
    {"cname": "Drab", "hex": "#828344"},
    {"cname": "Watermelon", "hex": "#Fd4659"},
    {"cname": "Reddish", "hex": "#C44240"},
    {"cname": "Lightblue", "hex": "#7bc8f6"},
    {"cname": "Burnt", "hex": "#B04e0f"},
    {"cname": "Blurple", "hex": "#5539cc"},
    {"cname": "Spearmint", "hex": "#1ef876"},
    {"cname": "Darkblue", "hex": "#030764"},
    {"cname": "Cerulean", "hex": "#0485d1"},
    {"cname": "Rosa", "hex": "#Fe86a4"},
    {"cname": "Sandy", "hex": "#F1da7a"},
    {"cname": "Algae", "hex": "#54ac68"},
    {"cname": "Olive", "hex": "#6e750e"},
    {"cname": "Cranberry", "hex": "#9e003a"},
    {"cname": "White", "hex": "#Ffffff"},
    {"cname": "MacAndCheese", "hex": "#Efb435"},
    {"cname": "Puce", "hex": "#A57e52"},
    {"cname": "Petrol", "hex": "#005f6a"},
    {"cname": "Heather", "hex": "#A484ac"},
    {"cname": "Wine", "hex": "#80013f"},
    {"cname": "Sunflower", "hex": "#Ffc512"},
    {"cname": "Cherry", "hex": "#Cf0234"},
    {"cname": "Snot", "hex": "#Acbb0d"},
    {"cname": "Melon", "hex": "#Ff7855"},
    {"cname": "Camel", "hex": "#C69f59"},
    {"cname": "Puke", "hex": "#A5a502"},
    {"cname": "Evergreen", "hex": "#05472a"},
    {"cname": "Avocado", "hex": "#90b134"},
    {"cname": "Buff", "hex": "#Fef69e"},
    {"cname": "Moss", "hex": "#769958"},
    {"cname": "Black", "hex": "#000000"},
    {"cname": "Mint", "hex": "#9ffeb0"},
    {"cname": "Periwinkle", "hex": "#8e82fe"},
    {"cname": "Dandelion", "hex": "#Fedf08"},
    {"cname": "Bluegreen", "hex": "#017a79"},
    {"cname": "Goldenrod", "hex": "#Fac205"},
    {"cname": "Stone", "hex": "#Ada587"},
    {"cname": "Kiwi", "hex": "#9cef43"},
    {"cname": "Celadon", "hex": "#Befdb7"},
    {"cname": "Bruise", "hex": "#7e4071"},
    {"cname": "Lichen", "hex": "#8fb67b"},
    {"cname": "Sea", "hex": "#3c9992"},
    {"cname": "Blood", "hex": "#770001"},
    {"cname": "Maroon", "hex": "#650021"},
    {"cname": "Carmine", "hex": "#9d0216"},
    {"cname": "Tomato", "hex": "#Ef4026"},
    {"cname": "Scarlet", "hex": "#Be0119"},
    {"cname": "Salmon", "hex": "#Ff796c"},
    {"cname": "Maize", "hex": "#F4d054"},
    {"cname": "Mustard", "hex": "#Ceb301"},
    {"cname": "Bland", "hex": "#Afa88b"},
    {"cname": "Peach", "hex": "#Ffb07c"},
    {"cname": "Iris", "hex": "#6258c4"},
    {"cname": "Lilac", "hex": "#Cea2fd"},
    {"cname": "Marigold", "hex": "#Fcc006"},
    {"cname": "Cream", "hex": "#Ffffc2"},
    {"cname": "Bordeaux", "hex": "#7b002c"},
    {"cname": "Mahogany", "hex": "#4a0100"},
    {"cname": "Dark", "hex": "#1b2431"},
    {"cname": "Greenblue", "hex": "#23c48b"},
    {"cname": "Orange", "hex": "#F97306"},
    {"cname": "Eggshell", "hex": "#Ffffd4"},
    {"cname": "Creme", "hex": "#Ffffb6"},
    {"cname": "Red", "hex": "#E50000"},
    {"cname": "Cyan", "hex": "#00ffff"},
    {"cname": "Teal", "hex": "#029386"},
    {"cname": "Mocha", "hex": "#9d7651"},
    {"cname": "Cerise", "hex": "#De0c62"},
    {"cname": "Eggplant", "hex": "#380835"},
    {"cname": "Greenish", "hex": "#40a368"},
    {"cname": "Adobe", "hex": "#Bd6c48"},
    {"cname": "Lavender", "hex": "#C79fef"},
    {"cname": "Apple", "hex": "#6ecb3c"},
    {"cname": "Steel", "hex": "#738595"},
    {"cname": "Tealish", "hex": "#24bca8"},
    {"cname": "Cocoa", "hex": "#875f42"},
    {"cname": "Aqua", "hex": "#13eac9"},
    {"cname": "Sandstone", "hex": "#C9ae74"},
    {"cname": "Golden", "hex": "#F5bf03"},
    {"cname": "Pink", "hex": "#Ff81c0"},
    {"cname": "Lightgreen", "hex": "#76ff7b"},
    {"cname": "Terracotta", "hex": "#Ca6641"},
    {"cname": "Purpleish", "hex": "#98568d"},
    {"cname": "Denim", "hex": "#3b638c"},
    {"cname": "Mulberry", "hex": "#920a4e"},
    {"cname": "Liliac", "hex": "#C48efd"},
    {"cname": "Toupe", "hex": "#C7ac7d"},
    {"cname": "Blush", "hex": "#F29e8e"},
    {"cname": "Pumpkin", "hex": "#E17701"},
    {"cname": "Grapefruit", "hex": "#Fd5956"},
    {"cname": "Lime", "hex": "#Aaff32"},
    {"cname": "Army", "hex": "#4b5d16"},
    {"cname": "Azul", "hex": "#1d5dec"},
    {"cname": "Caramel", "hex": "#Af6f09"},
    {"cname": "Dirt", "hex": "#8a6e45"},
    {"cname": "Earth", "hex": "#A2653e"},
    {"cname": "Apricot", "hex": "#Ffb16d"},
    {"cname": "Desert", "hex": "#Ccad60"},
    {"cname": "Grass", "hex": "#5cac2d"},
    {"cname": "Leaf", "hex": "#71aa34"},
    {"cname": "Ultramarine", "hex": "#2000b1"},
    {"cname": "Diarrhea", "hex": "#9f8303"},
    {"cname": "Shit", "hex": "#7f5f00"},
    {"cname": "Bubblegum", "hex": "#Ff6cb5"},
    {"cname": "Poop", "hex": "#7f5e00"},
    {"cname": "Booger", "hex": "#9bb53c"},
    {"cname": "Blue", "hex": "#0343df"},
    {"cname": "Putty", "hex": "#Beae8a"},
    {"cname": "Camo", "hex": "#7f8f4e"},
    {"cname": "Sky", "hex": "#82cafc"},
    {"cname": "Robin", "hex": "#6dedfd"},
    {"cname": "Pistachio", "hex": "#C0fa8b"},
    {"cname": "Tiffany", "hex": "#7bf2da"},
    {"cname": "Amber", "hex": "#Feb308"},
    {"cname": "Butter", "hex": "#Ffff81"},
    {"cname": "Vomit", "hex": "#A2a415"},
    {"cname": "Aquamarine", "hex": "#04d8b2"},
    {"cname": "Radioactive", "hex": "#2cfa1f"},
    {"cname": "Tea", "hex": "#65ab7c"},
    {"cname": "Taupe", "hex": "#B9a281"},
    {"cname": "Custard", "hex": "#Fffd78"},
    {"cname": "Violet", "hex": "#9a0eea"},
    {"cname": "Crimson", "hex": "#8c000f"},
    {"cname": "Aubergine", "hex": "#3d0734"},
    {"cname": "Velvet", "hex": "#750851"},
    {"cname": "Magenta", "hex": "#C20078"},
    {"cname": "Sage", "hex": "#87ae73"},
    {"cname": "Orchid", "hex": "#C875c4"},
    {"cname": "Emerald", "hex": "#01a049"},
    {"cname": "Dust", "hex": "#B2996e"},
    {"cname": "Mushroom", "hex": "#Ba9e88"},
    {"cname": "Butterscotch", "hex": "#Fdb147"},
    {"cname": "Mud", "hex": "#735c12"},
    {"cname": "Bluegrey", "hex": "#85a3b2"},
    {"cname": "Auburn", "hex": "#9a3001"},
    {"cname": "Dull", "hex": "#49759c"},
    {"cname": "Cornflower", "hex": "#6a79f7"},
    {"cname": "Greyish", "hex": "#A8a495"},
    {"cname": "Blueberry", "hex": "#464196"},
    {"cname": "Umber", "hex": "#B26400"},
    {"cname": "Azure", "hex": "#069af3"},
    {"cname": "Rouge", "hex": "#Ab1239"},
    {"cname": "Gold", "hex": "#Dbb40c"},
    {"cname": "Beige", "hex": "#E6daa6"},
    {"cname": "Merlot", "hex": "#730039"},
    {"cname": "Rust", "hex": "#A83c09"},
    {"cname": "Sand", "hex": "#E2ca76"},
    {"cname": "Carnation", "hex": "#Fd798f"},
    {"cname": "Greyblue", "hex": "#77a1b5"},
    {"cname": "Sienna", "hex": "#A9561e"},
    {"cname": "Pine", "hex": "#2b5d34"},
    {"cname": "Royal", "hex": "#0c1793"},
    {"cname": "Plum", "hex": "#580f41"},
    {"cname": "Cement", "hex": "#A5a391"},
    {"cname": "Indigo", "hex": "#380282"},
    {"cname": "Spruce", "hex": "#0a5f38"},
    {"cname": "Ocean", "hex": "#017b92"},
    {"cname": "Hunter", "hex": "#0b4008"},
    {"cname": "Chocolate", "hex": "#3d1c02"},
    {"cname": "Strawberry", "hex": "#Fb2943"},
    {"cname": "Wheat", "hex": "#Fbdd7e"},
    {"cname": "Jade", "hex": "#1fa774"},
    {"cname": "Dark-Fuchsia", "hex": "#9d0759"},
    {"cname": "Bronze", "hex": "#A87900"},
    {"cname": "Slate", "hex": "#516572"},
    {"cname": "Turquoise", "hex": "#06c2ac"},
    {"cname": "Orangered", "hex": "#Fe420f"},
    {"cname": "Banana", "hex": "#Ffff7e"},
    {"cname": "Parchment", "hex": "#Fefcaf"},
    {"cname": "Shamrock", "hex": "#01b44c"},
    {"cname": "Forest", "hex": "#0b5509"},
    {"cname": "Toxic", "hex": "#61de2a"},
    {"cname": "Claret", "hex": "#680018"},
    {"cname": "Burgundy", "hex": "#610023"},
    {"cname": "Burple", "hex": "#6832e3"},
    {"cname": "Marine", "hex": "#042e60"},
    {"cname": "Ochre", "hex": "#Bf9005"},
    {"cname": "Hazel", "hex": "#8e7618"},
    {"cname": "Squash", "hex": "#F2ab15"},
    {"cname": "Chartreuse", "hex": "#C1f80a"},
    {"cname": "Green", "hex": "#15b01a"},
    {"cname": "Ivory", "hex": "#Ffffcb"},
    {"cname": "Fuchsia", "hex": "#Ed0dd9"},
    {"cname": "Lemon", "hex": "#Fdff52"},
    {"cname": "Celery", "hex": "#C1fd95"},
    {"cname": "Yellow", "hex": "#Ffff14"},
    {"cname": "Fern", "hex": "#63a950"},
    {"cname": "Lipstick", "hex": "#D5174e"},
    {"cname": "Khaki", "hex": "#Aaa662"},
    {"cname": "Pear", "hex": "#Cbf85f"},
    {"cname": "Darkgreen", "hex": "#054907"},
    {"cname": "Pinky", "hex": "#Fc86aa"},
    {"cname": "Swamp", "hex": "#698339"},
    {"cname": "Wintergreen", "hex": "#20f986"},
    {"cname": "Manilla", "hex": "#Fffa86"},
    {"cname": "Mango", "hex": "#Ffa62b"},
    {"cname": "Amethyst", "hex": "#9b5fc0"},
    {"cname": "Canary", "hex": "#Fdff63"},
    {"cname": "Ruby", "hex": "#Ca0147"},
    {"cname": "Grey", "hex": "#929591"},
    {"cname": "Purple", "hex": "#7e1e9c"},
    {"cname": "Powder", "hex": "#B1d1fc"},
    {"cname": "Berry", "hex": "#990f4b"},
    {"cname": "Wisteria", "hex": "#A87dc2"},
    {"cname": "Straw", "hex": "#Fcf679"},
    {"cname": "Grape", "hex": "#6c3461"},
    {"cname": "Saffron", "hex": "#Feb209"},
    {"cname": "Heliotrope", "hex": "#D94ff5"},
    {"cname": "Yellowgreen", "hex": "#Bbf90f"},
    {"cname": "Orangeish", "hex": "#Fd8d49"},
    {"cname": "Purpley", "hex": "#8756e4"},
    {"cname": "Cinnamon", "hex": "#Ac4f06"},
    {"cname": "Barney", "hex": "#Ac1db8"},
    {"cname": "Brownish", "hex": "#9c6d57"},
    {"cname": "Brown", "hex": "#653700"},
    {"cname": "Pinkish", "hex": "#D46a7e"},
    {"cname": "Topaz", "hex": "#13bbaf"},
    {"cname": "Asparagus", "hex": "#77ab56"},
    {"cname": "Coral", "hex": "#Fc5a50"},
    {"cname": "Sapphire", "hex": "#2138ab"},
]
