M48
; DRILL file {KiCad (6.0.5)} date Sat Sep  9 17:34:26 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-09T17:34:26-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C4.500
%
G90
G05
T1
X103.545Y-66.255
X106.545Y-66.255
X194.62Y-79.07
X197.62Y-79.07
T2
X212.955Y-74.3
X219.955Y-74.3
T3
X121.78Y-71.6
T4
X90.599Y-64.477
X210.741Y-64.35
T0
M30
