name: Perform firmware build on the Intel NUC

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'board/**'
      - 'badge/**'
  push:
    paths:
      - '.github/workflows/esp32-build-self-hosted.yml'
      - 'board/**'
      - 'badge/**'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout MonkeyBadge
      uses: actions/checkout@v4

    - name: Unpack MicroPython
      run: |
         /usr/bin/tar zxf /opt/micropython.tgz

    - name: Set release date
      run: |
        echo "RELEASE_DATE=$(date +%Y-%m-%d.%s)" >> ${GITHUB_ENV}

    - name: Fix partition path
      run: |
        ln -sf ${{ github.workspace }}/board/monkeybadge-partitions.csv ${{ github.workspace }}/micropython/ports/esp32/monkeybadge-partitions.csv

    - name: Perform MicroPython Build
      run: |
        source /opt/espressif/esp-idf/export.sh
        make -C micropython/ports/esp32 BOARD_DIR=${{ github.workspace}}/board BOARD=monkeybadge CONFIG_APP_PROJECT_VER=${{ env.RELEASE_DATE }} all

    - name: Collect Assets
      run: |
        mkdir -p ${{ github.workspace }}/dist
        cp ${{ github.workspace }}/micropython/ports/esp32/build-monkeybadge/firmware.bin ${{ github.workspace }}/dist/firmware_${{ env.RELEASE_DATE }}.bin
        cp ${{ github.workspace }}/micropython/ports/esp32/build-monkeybadge/micropython.bin ${{ github.workspace }}/dist/ota_update_${{ env.RELEASE_DATE }}.bin
        SHA256SUM=$(sha256sum ${{ github.workspace }}/dist/ota_update_${{ env.RELEASE_DATE }}.bin | awk '{print $1}')
        FSIZE=$(find  -L * -name ota_update_${{ env.RELEASE_DATE }}.bin -printf '%s\n')
        jq  -n --arg fsize "${FSIZE}" --arg sha "${SHA256SUM}" --arg fname ota_update_${{ env.RELEASE_DATE }}.bin '{"firmware": $fname, "sha": $sha, "length": $fsize}' | tee ${{ github.workspace}}/dist/ota_update_${{ env.RELEASE_DATE }}.json
        echo "SHA256SUM=$SHA256SUM" | tee -a ${GITHUB_ENV}

    - name: Upload Artifacts - Zip Bundle
      uses: actions/upload-artifact@v3
      with:
        name: ota_update_${{ env.RELEASE_DATE }}
        path: ${{ github.workspace }}/dist/**

