name: Python code linting and formatting
on:
  push:
    paths: 
      - 'badge/**'
  pull_request:
    paths: 
      - 'badge/**'
  workflow_dispatch:

jobs:
  mpy_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install ruff==0.1.6
      - run: ruff check --output-format=github badge
      - run: ruff format --diff badge

